### ISSUE TITLE
[Bug] The CoordinatorServer failed to start due to the low zookeeper version

### ISSUE THREAD

**Issue by GangYang-HX** [alibaba/fluss#112]
### Search before asking

- [X] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.5.0

### Minimal reproduce step

The problem can be reproduced using a lower version of zk, such as zookeeper-3.4.6。

### What doesn't meet your expectations?

Abnormal screenshot
<img width="1248" alt="image" src="https://github.com/user-attachments/assets/70fa145e-7395-4b8e-b83d-75cbca6f91e9">

### Anything else?

It is recommended to clearly describe the minimum version requirements of ZooKeeper in the "Deploying Distributed Cluster" section, such as the JDK version requirements.
This allows users to use Fluss more quickly

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by luoyuxia** [comment]
closing since resolved
