### ISSUE TITLE
LazyMemorySegmentPool use BlockingQueue instead of using list with lock

### ISSUE THREAD

**Issue by swuferhong** [alibaba/fluss#14]
Currently, in `LazyMemorySegmentPool`, we use a List with a lock to manage cachePages. This approach requires the use of locks and manual writing await logic, which is not as efficient as using a `BlockingQueue`.  Moreover, replacing it with a `BlockingQueue` would not introduce any potential correctness issues.

**Comment by 0rrange** [comment]
I would like to do it.pls assign to me
