### ISSUE TITLE
[Bug] Log format equal to INDEXED does't support projection push down 

### ISSUE THREAD

**Issue by swuferhong** [alibaba/fluss#150]
### Search before asking

- [X] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.5.0

### Minimal reproduce step

You can create a Fluss table with option 'table.log.format' = 'INDEXED', and you will find you can not scan log from it while the Unsupported exception will be thrown.

### What doesn't meet your expectations?

Even if Fluss only support projection push down to server for log format as ARROW. However, INDEXED format also need to support projection push down in client side.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by wuchong** [comment]
Fixed in #151
