### ISSUE TITLE
[Bug] The MemoryLogRecordsArrowBuilder#getSizeInBytes() may cause CRC check error due to memory modifications after the builder is closed

### ISSUE THREAD

**Issue by swuferhong** [alibaba/fluss#152]
### Search before asking

- [X] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.5.0

### Minimal reproduce step

If you write logs in ARROW format, you are likely to encounter CRC checksum errors cause by this.

### What doesn't meet your expectations?

Currently, CRC checksum errors in server will throw if we use ARROW format to write log.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by wuchong** [comment]
Fixed in #153
