### ISSUE TITLE
[Bug] Lakehouse compaction service can't load hadoop plugin 

### ISSUE THREAD

**Issue by luoyuxia** [alibaba/fluss#178]
### Search before asking

- [X] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.5.0 

### Minimal reproduce step

Fluss use hdfs as remote storage, and start compaction service with `lakehouse.sh`.

### What doesn't meet your expectations?

Can't find the fluss-fs-hadoop plugin although it's in `plugins/hadoop` directory

### Anything else?

When it's hdfs as remote storage, the `lakehouse.sh` will just extract the `hdfs` scheme and try to find the hdfs plugin in directory `plugins/hdfs`, but it's in `plugins/hadoop`. Maybe we need do a mapping to map `hdfs`  to `hadoop`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by wuchong** [comment]
@luoyuxia shouldn't we rename the `plugins/hadoop` into `plugins/hdfs`? Because this is how the Filesystems find the plugins (using the scheme name as the directory name to find the plugin path).

**Comment by luoyuxia** [comment]
> @luoyuxia shouldn't we rename the `plugins/hadoop` into `plugins/hdfs`? Because this is how the Filesystems find the plugins (using the scheme name as the directory name to find the plugin path).

Not exactly using the scheme name as the directory name to find the plugin path, currently, the plugin discovery mechanism will visit all directories, and load plugin by SPI.

I think rename the `plugins/hadoop` into `plugins/hdfs` will be more clear since all other plugins use scheme name as the directory name. @michaelkoepf Could you please update your pr, we can just modify `plugins/hadoop/` to `plugins/hdfs` in `fluss-dist/../plugins.xml`.
