### ISSUE TITLE
[Bug]  cannot initialize module JavadocMethod - Property 'allowUndeclaredRTE' does not exist, please check the documentation

### ISSUE THREAD

**Issue by luoyuxia** [alibaba/fluss#220]
### Search before asking

- [X] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.5.0

### Minimal reproduce step

When I try to configure checkstyle for Java following the document  https://nightlies.apache.org/flink/flink-docs-master/docs/flinkdev/ide_setup/#checkstyle-for-java

My ide will thow:
```
 cannot initialize module JavadocMethod - Property 'allowUndeclaredRTE' does not exist, please check the documentation 
```
Seems the `10.18.2` don't support `allowUndeclaredRTE` any more...

https://stackoverflow.com/questions/59673419/how-can-i-fix-the-property-allowundeclaredrte-does-not-exist-error-when-usin

### What doesn't meet your expectations?

N/A

### Anything else?

1: degrade checkstyle version from `10.18.2`  any version prior to v8.24 in document
2: upgrade our checktyle version.
I'd like to upgrade our checktyle version since after I update may checkstyle plugin, there's no v8.24 version.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by psxjoy** [comment]
After reviewing Flink’s latest checkstyle file, I noticed that the `allowUndeclaredRTE` configuration has been removed. 
Updating the checkstyle file and aligning it with the latest plugin version seems like the optimal approach.

I’d be happy to take on updating the checkstyle.xml file. 
Feel free to assign this issue to me :)

**Comment by luoyuxia** [comment]
@psxjoy Thanks.. Assign to you..
