### ISSUE TITLE
[observability] Prometheus and Grafana as metrics monitoring stack

### ISSUE THREAD

**Issue by michaelkoepf** [alibaba/fluss#257]
### Search before asking

- [X] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Motivation

Fluss already exposes several metrics via Prometheus, but there is no way to visualize them yet.

### Solution

1. Provide Grafana dashboards for monitored metrics.
2. Provide a minimal configuration how for Prometheus + Grafana and show how to set it up in the [quickstart guide](https://alibaba.github.io/fluss-docs/docs/quickstart/flink/)

Dashboards:
- Overview dashboard with selected metrics
- Dashboard that shows [all metrics](https://alibaba.github.io/fluss-docs/docs/maintenance/monitor-metrics/#metrics-list)

### Willingness to contribute

- [X] I'm willing to submit a PR!

**Comment by polyzos** [comment]
This can be quite helpful and we could add Prometheus and Grafana into the docker-compose quickstart guide to make it easy for new users to test things out.

**Comment by polyzos** [comment]
@michaelkoepf It looks really good and all dashboards are working great .. big kudos for this 🚀 👍 

What I'm thinking though is to keep the quickstart guide as is to 1. keep it simple and 2. avoid resources for extra containers (for limited environments) and add the observability containers under the `monitor-metrics section` as complementary to the quickstart, i.e `based on the quick start guide you can add the prometheus and grafana ...`.

WDYT?
