### ISSUE TITLE
[Bug] Inconsistent Terminology Between "Random-Robin" Definition and Configuration Setting ("Random-Robin" vs "round_robin") Causes Reader Confusion

### ISSUE THREAD

**Issue by wangzhigang1999** [alibaba/fluss#52]
### Search before asking

- [X] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

No

### Minimal reproduce step

https://alibaba.github.io/fluss-docs/docs/table-design/data-distribution/bucketing/#random-robin-bucketing

### What doesn't meet your expectations?

https://alibaba.github.io/fluss-docs/docs/table-design/data-distribution/bucketing/#random-robin-bucketing

The terminology in the definition of "Random-Robin Bucketing" and its configuration instructions is inconsistent **("Random-Robin" vs "round_robin")**, which may lead to confusion for the reader.

![image](https://github.com/user-attachments/assets/0a028df2-2d6c-4202-8233-2dedc6acbac5)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by wuchong** [comment]
fixed by #54
